project:
  type: website
  output-dir: docs

website:
  title: "today"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - Test.qmd
      - href: nested/nested_file.qmd

format:
  html:
    theme: cosmo
    #css: styles.css
    toc: true